language: csharp
solution: Speakr.TalksApi.sln
mono: none
dotnet: 1.0.1
dist: trusty

env:
  - ARTIFACT_NAME=$(date +'TalksApi-%F')-${TRAVIS_BUILD_ID}

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - mysql -u root -e 'create database speakrdb;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - dotnet restore
  - dotnet build src/Speakr.TalksApi
  - dotnet build tests/Speakr.TalksApi.Tests
  - dotnet build tests/Speakr.TalksApi.AcceptanceTests
#  - dotnet test tests/Speakr.TalksApi.Tests
#  - dotnet test tests/Speakr.TalksApi.AcceptanceTests
  - dotnet run -p tests/Speakr.TalksApi.Tests/Speakr.TalksApi.Tests.csproj -f netcoreapp1.1
  - dotnet run -p tests/Speakr.TalksApi.AcceptanceTests/Speakr.TalksApi.AcceptanceTests.csproj -f netcoreapp1.1

before_deploy:
  - zip -r $ARTIFACT_NAME.zip *
  - mkdir -p CodeDeploy_Artifacts
  - mv $ARTIFACT_NAME.zip CodeDeploy_Artifacts/$ARTIFACT_NAME.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-1
    bucket: speakr-travisbuilds
    local_dir: CodeDeploy_Artifacts
    skip_cleanup: true
    upload-dir: TalksApi
    on: &2
        branch: production
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-1
    bucket: speakr-travisbuilds
    key: TalksApi/$ARTIFACT_NAME.zip
    application: speakr-talksapi-codedeploy
    deployment_group: speakr-talksapi-codedeploy-Fleet
    on: *2
